### ISSUE TITLE
Crash report when using too many Trades (calculation error with discount vouchers) 

### ISSUE THREAD

**Issue by MartinKBT** [CryptidID/Cryptid#2]
> Oops! The game crashed:
> card.lua:472: attempt to perform arithmetic on field 'discount_percent' (a nil value)
> 
> Additional Context:
> Balatro Version: 1.0.1f-FULL
> Modded Version: 1.0.0-ALPHA-0720a-STEAMODDED
> Love2D Version: 11.5.0
> Lovely Version: 0.5.0-beta4
> Steamodded Mods:
>     1: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Version: 0.4.3a]
>     2: Talisman by MathIsFun_, Mathguy24 [ID: Talisman, Version: 2.0.0-beta1]
> 
> Stack Traceback
> ===============
> (3) Lua upvalue 'sc' at file 'card.lua:472'
> Local variables:
>  self = table: 0x38036c28  {under_overlay:false, sort_id:216, click_offset:table: 0x38003a10, STATIONARY:false (more...)}
>  (*temporary) = Lua function '?' (defined at line 8101 of chunk main.lua)
>  (*temporary) = number: 1
>  (*temporary) = Lua function '?' (defined at line 7988 of chunk main.lua)
>  (*temporary) = number: 20.5
>  (*temporary) = nil
>  (*temporary) = eee16  {array:table: 0x37f538e8, sign:1}
>  (*temporary) = boolean: false
>  (*temporary) = eee16  {array:table: 0x37f538e8, sign:1}
>  (*temporary) = number: 2
>  (*temporary) = string: "attempt to perform arithmetic on field 'discount_percent' (a nil value)"
> (4) Lua upvalue 'sc' at line 1904 of chunk '"C:\Users\Martin Kubát\AppData\Roaming\Balatr..."]'
> Local variables:
>  self = table: 0x38036c28  {under_overlay:false, sort_id:216, click_offset:table: 0x38003a10, STATIONARY:false (more...)}
> (5) Lua method 'set_cost' at line 694 of chunk '"C:\Users\Martin Kubát\AppData\Roaming\Balatr..."]'
> Local variables:
>  self = table: 0x38036c28  {under_overlay:false, sort_id:216, click_offset:table: 0x38003a10, STATIONARY:false (more...)}
> (6) Lua field 'func' at line 587 of chunk '"C:\Users\Martin Kubát\AppData\Roaming\Balatr..."]'
> Local variables:
>  (for generator) = C function: next
>  (for state) = table: 0x38538578  {1:table: 0x38036c28, 2:table: 0x3830f8e8, 3:table: 0x38062878, 4:table: 0x3803a598 (more...)}
>  (for control) = number: nan
>  k = number: 1
>  v = table: 0x38036c28  {under_overlay:false, sort_id:216, click_offset:table: 0x38003a10, STATIONARY:false (more...)}
> (7) Lua method 'handle' at file 'engine/event.lua:99'
> Local variables:
>  self = table: 0x38e8c998  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x38741578 (more...)}
>  _results = table: 0x3876a1c8  {blocking:true, pause_skip:false, time_done:false, completed:false}
> (8) Lua method 'update' at file 'engine/event.lua:182'
> Local variables:
>  self = table: 0x37fa1128  {queue_last_processed:153.78333333335, queues:table: 0x38073c88, queue_dt:0.016666666666667 (more...)}
>  dt = number: 0.00684853
>  forced = nil
>  (for generator) = C function: next
>  (for state) = table: 0x38073c88  {unlock:table: 0x3804d020, other:table: 0x37fb3828, tutorial:table: 0x38051450 (more...)}
>  (for control) = number: nan
>  k = string: "base"
>  v = table: 0x380f6fd0  {1:table: 0x38036bb0, 2:table: 0x38e8c998, 3:table: 0x38230850, 4:table: 0x38d05540 (more...)}
>  blocked = boolean: false
>  i = number: 2
>  results = table: 0x3876a1c8  {blocking:true, pause_skip:false, time_done:false, completed:false}
> (9) Lua upvalue 'gameUpdateRef' at file 'game.lua:2652'
> Local variables:
>  self = table: 0x37ad7198  {PALETTE:table: 0x37bf83f8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
>  dt = number: 0.00684853
>  http_resp = nil
> (10) Lua upvalue 'upd' at file 'main.lua:479'
> Local variables:
>  self = table: 0x37ad7198  {PALETTE:table: 0x37bf83f8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
>  dt = number: 0.00684853
> (11) Lua upvalue 'upd' at file 'main.lua:8230'
> Local variables:
>  self = table: 0x37ad7198  {PALETTE:table: 0x37bf83f8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
>  dt = number: 0.00684853
> (12) Lua upvalue 'upd' at line 1038 of chunk '"C:\Users\Martin Kubát\AppData\Roaming\Balatr..."]'
> Local variables:
>  self = table: 0x37ad7198  {PALETTE:table: 0x37bf83f8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
>  dt = number: 0.00684853
> (13) Lua upvalue 'upd' at line 1917 of chunk '"C:\Users\Martin Kubát\AppData\Roaming\Balatr..."]'
> Local variables:
>  self = table: 0x37ad7198  {PALETTE:table: 0x37bf83f8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
>  dt = number: 0.00684853
> (14) Lua method 'update' at file 'Cryptid.lua:633' (from mod with id Cryptid)
> Local variables:
>  self = table: 0x37ad7198  {PALETTE:table: 0x37bf83f8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
>  dt = number: 0.00684853
> (15) Lua field 'update' at file 'main.lua:133'
> Local variables:
>  dt = number: 0.00684853
> (16) Lua function '?' at file 'main.lua:77' (best guess)
> (17) global C function 'xpcall'
> (18) Love2D function at file 'boot.lua:377' (best guess)
> Local variables:
>  func = Lua function '?' (defined at line 48 of chunk main.lua)
>  inerror = boolean: true
>  deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
>  earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
> 

This happened when I made infinity Trade cards with CCD deck. Once I lose Voucher which discounts shop by 50% game crashes

**Comment by Emyrk** [comment]
What? You have the wrong project
